# Generated by Django 6.0.1 on 2026-01-26 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accountsecurity",
            name="activation_code_verified",
        ),
        migrations.RemoveField(
            model_name="accountsecurity",
            name="imf_code_verified",
        ),
        migrations.RemoveField(
            model_name="accountsecurity",
            name="tax_code_verified",
        ),
        migrations.AddField(
            model_name="accountsecurity",
            name="verified_devices",
            field=models.JSONField(default=dict),
        ),
    ]
