# Generated by Django 6.0.1 on 2026-01-26 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_accountsecurity_activation_code_verified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactionsettings",
            name="enable_transaction_code",
            field=models.BooleanField(default=True),
        ),
    ]
