# Generated by Django 6.0.1 on 2026-01-26 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_transactionsettings_enable_transaction_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactionsettings",
            name="account",
            field=models.OneToOneField(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transaction_settings",
                to="api.account",
            ),
            preserve_default=False,
        ),
    ]
