# Generated by Django 5.2.3 on 2025-06-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_transfer_external_receiver_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='account',
            field=models.CharField(default='Unknown', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transfer',
            name='address',
            field=models.CharField(default='Unknown', max_length=225),
        ),
        migrations.AddField(
            model_name='transfer',
            name='bank_name',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
    ]
