# Generated by Django 6.0.1 on 2026-01-26 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_transactionsettings_account"),
    ]

    operations = []
