# Generated by Django 6.0.1 on 2026-01-26 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_create_transaction_settings_for_existing_accounts"),
    ]

    operations = []
