# Generated by Django 5.2.3 on 2025-06-14 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_account_account_number_account_apt_suite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='swift_code',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
