# Generated by Django 5.2.3 on 2025-06-14 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_transfer_swift_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='bank_account',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
