# Generated by Django 5.2.3 on 2025-06-14 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_transfer_bank_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='account',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='address',
        ),
    ]
