# Generated by Django 5.2.3 on 2025-06-14 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_transfer_account_remove_transfer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='account',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
