# Generated by Django 5.2.3 on 2025-06-14 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_transfer_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfer',
            old_name='note',
            new_name='purpose',
        ),
        migrations.RenameField(
            model_name='transfer',
            old_name='bank_name',
            new_name='receiver_bank',
        ),
        migrations.RenameField(
            model_name='transfer',
            old_name='external_receiver_name',
            new_name='receiver_name',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='bank_account',
        ),
        migrations.AddField(
            model_name='transfer',
            name='receiver_account',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
