# Generated by Django 5.2.3 on 2025-06-14 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_note_transfer_purpose_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposit',
            old_name='note',
            new_name='purpose',
        ),
    ]
