# Generated by Django 5.2.3 on 2025-06-16 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_account_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='code_entered',
            field=models.BooleanField(default=False),
        ),
    ]
