# Generated by Django 5.2.3 on 2025-06-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_transfer_code_entered'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='recipient_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
