# Generated by Django 5.2.3 on 2025-06-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_transfer_recipient_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='iban',
            field=models.CharField(blank=True, max_length=34, null=True),
        ),
    ]
