# Generated by Django 5.2.3 on 2025-06-19 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_transfer_nationality_transfer_zip_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='state',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
