# Generated by Django 5.2.3 on 2025-06-19 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_transfer_state_alter_transfer_swift_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='city',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
