# Generated by Django 6.0.1 on 2026-01-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_account_nationality_alter_transfer_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_transfer_locked',
            field=models.BooleanField(default=False),
        ),
    ]
