# Generated by Django 6.0.1 on 2026-01-17 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_customuser_is_transfer_locked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='iban',
        ),
    ]
