# Generated by Django 6.0.1 on 2026-01-25 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_customuser_verification_code_sent_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='verification_code_expired',
        ),
    ]
